ARM: mach-imx: Disable busfreq driver
Building just IMX6UL causes linker errors:
  arch/arm/mach-imx/busfreq_ddr3.o: in function `init_mmdc_ddr3_settings_imx6_up':
  busfreq_ddr3.c:(.text+0x590): undefined reference to `imx6_up_ddr3_freq_change'

So it seems to be not properly tested on IMX6UL. To be on the safe side,
disable it completely.

Signed-off-by: Stefan Wahren <stefan.wahren@chargebyte.com>